## Baidu top 50 headline
baidu.com

### Part 1 - Set up

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" 
}

response = requests.get("https://top.baidu.com/board?tab=realtime", headers=headers)
doc = BeautifulSoup(response.text, 'html.parser')

response.status_code   # 200 means OK

200

### Part 2 - Identiy the loop structure

In [3]:
headlines = doc.find_all("div", class_ ="category-wrap_iQLoo")   # 51 items

In [4]:
len(headlines)

51

In [5]:
headlines[1]

<div class="category-wrap_iQLoo horizontal_1eKyQ"> <a class="img-wrapper_29V76" href="https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%E5%BC%80%E8%B5%9B%E5%90%8E%E6%9C%80%E7%96%AF%E7%8B%82%E4%B8%80%E6%88%98%E8%AF%9E%E7%94%9F&amp;sa=fyb_news&amp;rsv_dl=fyb_news" target="_blank"> <div class="index_1Ew5p c-index-bg1">  1 </div> <img alt="" src="https://fyb-2.cdn.bcebos.com/hotboard_image/28f62b67bf27dc0a7f545061f23ba943?x-bce-process=image/resize,m_fill,w_256,h_170"/> <div class="border_3WfEn"></div> </a> <div class="trend_2RttY hide-icon_3uwiZ"> <div class="img-wrap_JPOmE trend-icon_1Z3Cd"> <img src="//fyb-pc-static.cdn.bcebos.com/static/asset/icon-same_886375f242bd1538af21a9721f16b170.png"/> </div> <div class="hot-index_1Bl1a"> 7809561 </div> <div class="text_1lUwZ"> 热搜指数 </div> </div> <img class="line_3-bzA" src="//fyb-pc-static.cdn.bcebos.com/static/asset/line-bg@2x_95cb5a089159c6d5a959a596d460d60a.png"/> <div class="content_1YWBm"> <a class="title_dIF3B" href="https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%E5%BC%80%E8%B5%9B%E5%90%8E%E6%9C%80%E7%96%AF%E7%8B%82%E4%B8%80%E6%88%98%E8%AF%9E%E7%94%9F&amp;sa=fyb_news&amp;rsv_dl=fyb_news" target="_blank"> <div class="c-single-text-ellipsis">  世界杯开赛后最疯狂一战诞生 </div> <div class="c-text c-text-hot_3ZhI9 hot-tag_1G080"> 热 </div> </a> <!--s-frag--> <div class="hot-desc_1m_jR small_Uvkd3 ellipsis_DupbZ"> 在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取得首胜。根据统计，这是世界杯... <a class="look-more_3oNWC" href="https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%E5%BC%80%E8%B5%9B%E5%90%8E%E6%9C%80%E7%96%AF%E7%8B%82%E4%B8%80%E6%88%98%E8%AF%9E%E7%94%9F&amp;sa=fyb_news&amp;rsv_dl=fyb_news" target="_blank">查看更多&gt;</a> </div> <div class="hot-desc_1m_jR large_nSuFU ellipsis_DupbZ"> 在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取得首胜。根据统计，这是世界杯史上除了加时赛之外，第一场出... <a class="look-more_3oNWC" href="https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%E5%BC%80%E8%B5%9B%E5%90%8E%E6%9C%80%E7%96%AF%E7%8B%82%E4%B8%80%E6%88%98%E8%AF%9E%E7%94%9F&amp;sa=fyb_news&amp;rsv_dl=fyb_news" target="_blank">查看更多&gt;</a> </div> <!--/s-frag--> </div> </div>

In [7]:
rows = []
for headline in headlines:
    row = {}

    try:
        row['rank'] = headline.find(class_ = 'index_1Ew5p').text.strip()
    except:
        row['rank'] = None

    row ['title'] = headline.find(class_ ="c-single-text-ellipsis").text.strip()
    
    try: 
        row['subhead'] = headline.find(class_ ='hot-desc_1m_jR').text.strip()
    except:
        row['subhead'] = None

    try:
        row['count'] = headline.find(class_ = 'hot-index_1Bl1a').text.strip()
    except:
        row['count'] = None


    try:
        row['tag'] = headline.find(class_ = 'c-text').text.strip()
    except:
        row['tag'] = None

    try:
        row['link'] = headline.find('a')['href']
    except:
        row['link'] = None


    # try:
    #     row['premium'] = story.find(class_ = 'sr-only').text
    # except:
    #     row['premium'] = None
    
    


    # try:
    #     row['byline'] = story.find(class_ = 'article__byline').text.strip()
    # except:
    #     row['byline'] = None
    
    # img = story.find("img")
    # try:
    #    row['image_url'] = story.find('img')['src']
    # except:
    #    row['image'] = None

    # try:
    #     row['article_type'] = story.find(class_ = 'article__type').text
    # except:
    #     row['article_type'] = None





    rows.append(row)


len(rows)

51

In [8]:
rows

[{'rank': '',
  'title': '家国总关情',
  'subhead': '家国情怀，始终是端午节不变的底色，时隔千年依然引人共鸣。习近平总书记曾深刻指出：“我们是中华儿女，要了解中华民族历史，秉... 查看更多>',
  'count': '7904126',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%AE%B6%E5%9B%BD%E6%80%BB%E5%85%B3%E6%83%85&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '1',
  'title': '世界杯开赛后最疯狂一战诞生',
  'subhead': '在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取得首胜。根据统计，这是世界杯... 查看更多>',
  'count': '7809561',
  'tag': '热',
  'link': 'https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%E5%BC%80%E8%B5%9B%E5%90%8E%E6%9C%80%E7%96%AF%E7%8B%82%E4%B8%80%E6%88%98%E8%AF%9E%E7%94%9F&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '2',
  'title': '缅甸总统在上海感叹中国太发达了',
  'subhead': '6月18日，缅甸总统敏昂莱到访上海临港新片区参观考察，并让随行人员多学习：中国太发达了！ 查看更多>',
  'count': '7713263',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E7%BC%85%E7%94%B8%E6%80%BB%E7%BB%9F%E5%9C%A8%E4%B8%8A%E6%B5%B7%E6%84%9F%E5%8F%B9%E4%B8%AD%E5%9B%BD%E5%A4%AA%E5%8F%91%E8%BE%BE%E4%BA%86&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '3',
  'title': '端午节最硬核的“龙舟”竞渡来了',
  'subhead': '又到一年端午时，一起来看最硬核的“龙舟”竞渡。 查看更多>',
  'count': '7616958',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E7%AB%AF%E5%8D%88%E8%8A%82%E6%9C%80%E7%A1%AC%E6%A0%B8%E7%9A%84%E2%80%9C%E9%BE%99%E8%88%9F%E2%80%9D%E7%AB%9E%E6%B8%A1%E6%9D%A5%E4%BA%86&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '4',
  'title': '159瓶茅台被扣押3年后失踪？警方通报',
  'subhead': '6月18日，四川宜宾警方通报“159瓶茅台被扣押3年后失踪”相关情况称，涉案酒品于2023年被依法扣押并完成鉴定，除抽样... 查看更多>',
  'count': '7520827',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=159%E7%93%B6%E8%8C%85%E5%8F%B0%E8%A2%AB%E6%89%A3%E6%8A%BC3%E5%B9%B4%E5%90%8E%E5%A4%B1%E8%B8%AA%EF%BC%9F%E8%AD%A6%E6%96%B9%E9%80%9A%E6%8A%A5&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '5',
  'title': '男子吃野生菌后报警：家被虫入侵了',
  'subhead': '6月18日，云南一男子食用野生菌中毒出现幻觉，报警称家里被虫入侵，民警上门带他送医检查。 查看更多>',
  'count': '7425541',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E7%94%B7%E5%AD%90%E5%90%83%E9%87%8E%E7%94%9F%E8%8F%8C%E5%90%8E%E6%8A%A5%E8%AD%A6%EF%BC%9A%E5%AE%B6%E8%A2%AB%E8%99%AB%E5%85%A5%E4%BE%B5%E4%BA%86&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '6',
  'title': '世界杯：墨西哥vs韩国',
  'subhead': '北京时间6月19日9:00，世界杯小组赛A组第二轮，墨西哥vs韩国。 查看更多>',
  'count': '7333519',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%E6%9D%AF%EF%BC%9A%E5%A2%A8%E8%A5%BF%E5%93%A5vs%E9%9F%A9%E5%9B%BD&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '7',
  'title': '粽叶飘香 端午安康',
  'subhead': '端午节历史悠久，意蕴丰富，是中国四大传统节日之一，亦是中国首个入选联合国教科文组织人类非物质文化遗产代表作名录的节日。赛... 查看更多>',
  'count': '7238810',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E7%B2%BD%E5%8F%B6%E9%A3%98%E9%A6%99+%E7%AB%AF%E5%8D%88%E5%AE%89%E5%BA%B7&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '8',
  'title': '周冬雨被曝演话剧不背台词 观众发声',
  'subhead': '近日，周冬雨、段奕宏、陈明昊主演的话剧《文城》在秦皇岛上演，票价区间为480元至880元，有观众爆料周冬雨演话剧不背台词... 查看更多>',
  'count': '7139093',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E5%91%A8%E5%86%AC%E9%9B%A8%E8%A2%AB%E6%9B%9D%E6%BC%94%E8%AF%9D%E5%89%A7%E4%B8%8D%E8%83%8C%E5%8F%B0%E8%AF%8D+%E8%A7%82%E4%BC%97%E5%8F%91%E5%A3%B0&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '9',
  'title': '伊朗最高领袖对伊美备忘录持不同意见',
  'subhead': '查看更多>',
  'count': '7045656',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E4%BC%8A%E6%9C%97%E6%9C%80%E9%AB%98%E9%A2%86%E8%A2%96%E5%AF%B9%E4%BC%8A%E7%BE%8E%E5%A4%87%E5%BF%98%E5%BD%95%E6%8C%81%E4%B8%8D%E5%90%8C%E6%84%8F%E8%A7%81&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '10',
  'title': '卡塔尔0比6惨败加拿大',
  'subhead': '北京时间6月19日清晨6点，2026年世界杯B组东道主加拿大vs卡塔尔。这场比赛上演“进球+红牌大战”。最终，以多打少的... 查看更多>',
  'count': '6953298',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%8D%A1%E5%A1%94%E5%B0%940%E6%AF%946%E6%83%A8%E8%B4%A5%E5%8A%A0%E6%8B%BF%E5%A4%A7&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '11',
  'title': '工信部辟谣8家车企被撤销资质',
  'subhead': '6月18日，针对“8家车企被移出名录、整车生产资质永久失效”的网传消息，工信部回应称相关说法不实。除一汽夏利早年已注销准... 查看更多>',
  'count': '6849341',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%B7%A5%E4%BF%A1%E9%83%A8%E8%BE%9F%E8%B0%A38%E5%AE%B6%E8%BD%A6%E4%BC%81%E8%A2%AB%E6%92%A4%E9%94%80%E8%B5%84%E8%B4%A8&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '12',
  'title': 'C罗丢球后问门将：为何不出击',
  'subhead': '6月18日，美加墨世界杯K组首轮，葡萄牙1比1战平民主刚果。上半场补时阶段球队角球失守后，C罗第一时间走向门将迪奥戈·科... 查看更多>',
  'count': '6753240',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=C%E7%BD%97%E4%B8%A2%E7%90%83%E5%90%8E%E9%97%AE%E9%97%A8%E5%B0%86%EF%BC%9A%E4%B8%BA%E4%BD%95%E4%B8%8D%E5%87%BA%E5%87%BB&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '13',
  'title': '高考试卷原来是这样打分的',
  'subhead': '查看更多>',
  'count': '6658588',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E9%AB%98%E8%80%83%E8%AF%95%E5%8D%B7%E5%8E%9F%E6%9D%A5%E6%98%AF%E8%BF%99%E6%A0%B7%E6%89%93%E5%88%86%E7%9A%84&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '14',
  'title': '你支持“咸粽”还是“甜粽”',
  'subhead': '近日，端午节再度掀起“咸甜粽之争”。有人偏爱咸粽的鲜香满足，也有人坚持甜粽的软糯清甜，不同地域和饮食习惯让口味选择各不相... 查看更多>',
  'count': '6571116',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%BD%A0%E6%94%AF%E6%8C%81%E2%80%9C%E5%92%B8%E7%B2%BD%E2%80%9D%E8%BF%98%E6%98%AF%E2%80%9C%E7%94%9C%E7%B2%BD%E2%80%9D&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '15',
  'title': '加拿大球员重伤 小腿变形',
  'subhead': '6月19日，世界杯小组赛第二轮：加拿大vs卡塔尔，卡塔尔中场阿西姆·马迪博在一次拼抢中，一脚踢在了加拿大中场伊斯梅尔·科... 查看更多>',
  'count': '6476777',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%90%83%E5%91%98%E9%87%8D%E4%BC%A4+%E5%B0%8F%E8%85%BF%E5%8F%98%E5%BD%A2&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '16',
  'title': '贾乃亮自曝无戏可拍',
  'subhead': '查看更多>',
  'count': '6369377',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%B4%BE%E4%B9%83%E4%BA%AE%E8%87%AA%E6%9B%9D%E6%97%A0%E6%88%8F%E5%8F%AF%E6%8B%8D&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '17',
  'title': '民房“一窗6店” 被质疑是幽灵外卖',
  'subhead': '近日，广东东莞一处民房通过单一窗户同时运营6家外卖店铺，外卖员反映店铺前后门紧闭，餐食仅通过窗口递出，且无法查看后厨情况... 查看更多>',
  'count': '6274658',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E6%B0%91%E6%88%BF%E2%80%9C%E4%B8%80%E7%AA%976%E5%BA%97%E2%80%9D+%E8%A2%AB%E8%B4%A8%E7%96%91%E6%98%AF%E5%B9%BD%E7%81%B5%E5%A4%96%E5%8D%96&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '18',
  'title': '未来5年 找工作关注这些行业领域',
  'subhead': '日前，国务院印发《实施就业优先战略“十五五”规划》。文件提到哪些行业领域，蕴藏哪些就业机会？未来5年，找工作关注哪些行业... 查看更多>',
  'count': '6183335',
  'tag': '热',
  'link': 'https://www.baidu.com/s?wd=%E6%9C%AA%E6%9D%A55%E5%B9%B4+%E6%89%BE%E5%B7%A5%E4%BD%9C%E5%85%B3%E6%B3%A8%E8%BF%99%E4%BA%9B%E8%A1%8C%E4%B8%9A%E9%A2%86%E5%9F%9F&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '19',
  'title': '这种粽子绳高温蒸煮有毒',
  'subhead': '市场上有不少品牌的散装粽子，会用尼龙绳或塑料绳捆绑，有的还贴上塑料标签。据了解，化学纤维绳安全性较差，如尼龙绳、涤纶绳、... 查看更多>',
  'count': '6089819',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%BF%99%E7%A7%8D%E7%B2%BD%E5%AD%90%E7%BB%B3%E9%AB%98%E6%B8%A9%E8%92%B8%E7%85%AE%E6%9C%89%E6%AF%92&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '20',
  'title': '替补19分钟双响 最贵天才拯救瑞士',
  'subhead': '6月19日，世界杯B组第二轮，瑞士4比1击败波黑取得首胜。20岁的曼赞比第71分钟替补登场，在19分钟内完成梅开二度，帮... 查看更多>',
  'count': '5982946',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%9B%BF%E8%A1%A519%E5%88%86%E9%92%9F%E5%8F%8C%E5%93%8D+%E6%9C%80%E8%B4%B5%E5%A4%A9%E6%89%8D%E6%8B%AF%E6%95%91%E7%91%9E%E5%A3%AB&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '21',
  'title': '记者网购7支大牌口红仅1支鉴定为真',
  'subhead': '近日，武汉一消费者怀疑通过闪购买到假口红，引发关注。记者随后网购7支低价大牌口红进行验证，并送交第三方平台鉴定，结果仅1... 查看更多>',
  'count': '5889701',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%AE%B0%E8%80%85%E7%BD%91%E8%B4%AD7%E6%94%AF%E5%A4%A7%E7%89%8C%E5%8F%A3%E7%BA%A2%E4%BB%851%E6%94%AF%E9%89%B4%E5%AE%9A%E4%B8%BA%E7%9C%9F&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '22',
  'title': '2026香港小姐12强出炉 硕士生超半数',
  'subhead': '6月17日，《2026香港小姐竞选》12强佳丽在将军澳电视城亮相，超半数选手为硕士毕业生，包括袁丝珩、李泽欣等。此前大热... 查看更多>',
  'count': '5793385',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=2026%E9%A6%99%E6%B8%AF%E5%B0%8F%E5%A7%9012%E5%BC%BA%E5%87%BA%E7%82%89+%E7%A1%95%E5%A3%AB%E7%94%9F%E8%B6%85%E5%8D%8A%E6%95%B0&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '23',
  'title': '莫斯科遭2年来最大规模无人机袭击',
  'subhead': '当地时间6月18日，莫斯科遭遇近两年来最大规模无人机袭击，乌克兰无人机击中卡波特尼亚区炼油厂及萨多沃德购物中心，致储油罐... 查看更多>',
  'count': '5716214',
  'tag': '热',
  'link': 'https://www.baidu.com/s?wd=%E8%8E%AB%E6%96%AF%E7%A7%91%E9%81%AD2%E5%B9%B4%E6%9D%A5%E6%9C%80%E5%A4%A7%E8%A7%84%E6%A8%A1%E6%97%A0%E4%BA%BA%E6%9C%BA%E8%A2%AD%E5%87%BB&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '24',
  'title': '挪威球迷荡起双桨助威动作全网刷屏',
  'subhead': '挪威队目前正在备战第二轮对阵塞内加尔的小组赛次轮，首轮比赛除了哈兰德的精彩表现之外，挪威球迷“荡起双桨”的助威动作也全网... 查看更多>',
  'count': '5601253',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%8C%AA%E5%A8%81%E7%90%83%E8%BF%B7%E8%8D%A1%E8%B5%B7%E5%8F%8C%E6%A1%A8%E5%8A%A9%E5%A8%81%E5%8A%A8%E4%BD%9C%E5%85%A8%E7%BD%91%E5%88%B7%E5%B1%8F&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '25',
  'title': '美加墨世界杯首位女主裁亮相',
  'subhead': '北京时间6月19日凌晨，美加墨世界杯A组第二轮比赛，捷克队对阵南非队的比赛在亚特兰大体育场举行。值得关注的是，托莉·彭索... 查看更多>',
  'count': '5507107',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E7%BE%8E%E5%8A%A0%E5%A2%A8%E4%B8%96%E7%95%8C%E6%9D%AF%E9%A6%96%E4%BD%8D%E5%A5%B3%E4%B8%BB%E8%A3%81%E4%BA%AE%E7%9B%B8&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '26',
  'title': '加拿大球员目睹队友受伤吓哭',
  'subhead': '美加墨世界杯小组赛B组第2轮，加拿大vs卡塔尔。比赛第53分钟，卡塔尔中场阿西姆·马迪博拼抢中对伊斯梅尔·科内犯规，导致... 查看更多>',
  'count': '5432080',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%8A%A0%E6%8B%BF%E5%A4%A7%E7%90%83%E5%91%98%E7%9B%AE%E7%9D%B9%E9%98%9F%E5%8F%8B%E5%8F%97%E4%BC%A4%E5%90%93%E5%93%AD&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '27',
  'title': '李佳琦回应纸尿裤被指检出甲酰胺',
  'subhead': '近日，“好奇”“碧芭宝贝”“Babycare”等多个品牌的婴幼儿纸尿裤中被曝检出毒性物质——甲酰胺。6月18日，李佳琦在... 查看更多>',
  'count': '5335826',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%9D%8E%E4%BD%B3%E7%90%A6%E5%9B%9E%E5%BA%94%E7%BA%B8%E5%B0%BF%E8%A3%A4%E8%A2%AB%E6%8C%87%E6%A3%80%E5%87%BA%E7%94%B2%E9%85%B0%E8%83%BA&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '28',
  'title': '韩总统抓空档快步上前与卢拉交流',
  'subhead': '查看更多>',
  'count': '5233693',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E9%9F%A9%E6%80%BB%E7%BB%9F%E6%8A%93%E7%A9%BA%E6%A1%A3%E5%BF%AB%E6%AD%A5%E4%B8%8A%E5%89%8D%E4%B8%8E%E5%8D%A2%E6%8B%89%E4%BA%A4%E6%B5%81&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '29',
  'title': '卖不完的粽子都去哪儿了',
  'subhead': '每年端午节前后都会有大量粽子上市。许多人心中都有一个疑问：卖不完的粽子最终都去了哪里？记者实地调查发现，有的被转售给早餐... 查看更多>',
  'count': '5121672',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%8D%96%E4%B8%8D%E5%AE%8C%E7%9A%84%E7%B2%BD%E5%AD%90%E9%83%BD%E5%8E%BB%E5%93%AA%E5%84%BF%E4%BA%86&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '30',
  'title': '伊朗：霍尔木兹海峡60天内免费通行',
  'subhead': '据伊朗伊斯兰共和国通讯社18日报道，伊朗最高国家安全委员会发表声明说，根据伊美谅解备忘录，在未来60天内，申请通过霍尔木... 查看更多>',
  'count': '5032160',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%BC%8A%E6%9C%97%EF%BC%9A%E9%9C%8D%E5%B0%94%E6%9C%A8%E5%85%B9%E6%B5%B7%E5%B3%A160%E5%A4%A9%E5%86%85%E5%85%8D%E8%B4%B9%E9%80%9A%E8%A1%8C&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '31',
  'title': '小组赛首轮后男足世界排名情况',
  'subhead': '近日，2026美加墨世界杯小组赛第二轮开启。首轮结束后最新世界排名出炉，阿根廷继续领跑，法国反超西班牙升至第二。墨西哥、... 查看更多>',
  'count': '4938649',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%B0%8F%E7%BB%84%E8%B5%9B%E9%A6%96%E8%BD%AE%E5%90%8E%E7%94%B7%E8%B6%B3%E4%B8%96%E7%95%8C%E6%8E%92%E5%90%8D%E6%83%85%E5%86%B5&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '32',
  'title': '老外在世界杯被中国拨浪鼓硬控',
  'subhead': '近日，美加墨世界杯举行，老外在世界杯被中国拨浪鼓硬控了！ 查看更多>',
  'count': '4845353',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%80%81%E5%A4%96%E5%9C%A8%E4%B8%96%E7%95%8C%E6%9D%AF%E8%A2%AB%E4%B8%AD%E5%9B%BD%E6%8B%A8%E6%B5%AA%E9%BC%93%E7%A1%AC%E6%8E%A7&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '33',
  'title': '刘建宏：C罗该给葡萄牙打替补',
  'subhead': '北京时间6月18日，世界杯小组赛首轮，葡萄牙1-1民主刚果，C罗没有进球，表现低迷，前央视名嘴刘建宏用大巴黎举例，认为C... 查看更多>',
  'count': '4744952',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%88%98%E5%BB%BA%E5%AE%8F%EF%BC%9AC%E7%BD%97%E8%AF%A5%E7%BB%99%E8%91%A1%E8%90%84%E7%89%99%E6%89%93%E6%9B%BF%E8%A1%A5&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '34',
  'title': '韩国门将超级失误',
  'subhead': '6月19日的世界杯比赛，韩国门将金承奎接球脱手，导致墨西哥队比分领先。詹俊：超级失误！ 查看更多>',
  'count': '4655116',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E9%9F%A9%E5%9B%BD%E9%97%A8%E5%B0%86%E8%B6%85%E7%BA%A7%E5%A4%B1%E8%AF%AF&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '35',
  'title': '本届世界杯红牌数已超上届',
  'subhead': '北京时间2026年6月19日，卡塔尔球员红牌被罚下，本届世界杯的红牌数量已来到5张，超过了2022年卡塔尔世界杯的4张红... 查看更多>',
  'count': '4558528',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%9C%AC%E5%B1%8A%E4%B8%96%E7%95%8C%E6%9D%AF%E7%BA%A2%E7%89%8C%E6%95%B0%E5%B7%B2%E8%B6%85%E4%B8%8A%E5%B1%8A&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '36',
  'title': '60后大爷看00后龙舟男团的腹肌笑了',
  'subhead': '6月18日，杭州一场龙舟活动中，60后大爷观看00后龙舟男团训练时，因年轻队员的腹肌发出爽朗笑声，展现新老两代龙舟爱好者... 查看更多>',
  'count': '4479736',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=60%E5%90%8E%E5%A4%A7%E7%88%B7%E7%9C%8B00%E5%90%8E%E9%BE%99%E8%88%9F%E7%94%B7%E5%9B%A2%E7%9A%84%E8%85%B9%E8%82%8C%E7%AC%91%E4%BA%86&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '37',
  'title': '追觅宣布回归主业',
  'subhead': '近期，追觅科技完成新一轮核心战略调整，锁定智能家庭、户外庭院、智能出行、具身智能4大核心赛道，对旗下业务体系进行系统性梳... 查看更多>',
  'count': '4371409',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%BF%BD%E8%A7%85%E5%AE%A3%E5%B8%83%E5%9B%9E%E5%BD%92%E4%B8%BB%E4%B8%9A&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '38',
  'title': '多国强烈谴责以色列定居者袭击行为',
  'subhead': '当地时间18日，约旦、阿联酋、印度尼西亚、巴基斯坦、土耳其、沙特阿拉伯、卡塔尔和埃及八国发表联合声明，强烈谴责以色列定居... 查看更多>',
  'count': '4282261',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E5%A4%9A%E5%9B%BD%E5%BC%BA%E7%83%88%E8%B0%B4%E8%B4%A3%E4%BB%A5%E8%89%B2%E5%88%97%E5%AE%9A%E5%B1%85%E8%80%85%E8%A2%AD%E5%87%BB%E8%A1%8C%E4%B8%BA&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '39',
  'title': '多名学生违背张桂梅忠告回到大山',
  'subhead': '多名从云南华坪女子高中毕业的学生违背校长张桂梅“走出大山后不要回来”的忠告，主动返乡担任教师、医生等基层职业。张桂梅从最... 查看更多>',
  'count': '4189110',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%E5%A4%9A%E5%90%8D%E5%AD%A6%E7%94%9F%E8%BF%9D%E8%83%8C%E5%BC%A0%E6%A1%82%E6%A2%85%E5%BF%A0%E5%91%8A%E5%9B%9E%E5%88%B0%E5%A4%A7%E5%B1%B1&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '40',
  'title': '#端午放粽民俗有多上头#',
  'subhead': '查看更多>',
  'count': '4073268',
  'tag': '新',
  'link': 'https://www.baidu.com/s?wd=%23%E7%AB%AF%E5%8D%88%E6%94%BE%E7%B2%BD%E6%B0%91%E4%BF%97%E6%9C%89%E5%A4%9A%E4%B8%8A%E5%A4%B4%23&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '41',
  'title': '《给阿嬷的情书》全球上映大马观众泪目',
  'subhead': '《给阿嬷的情书》全球上映，大马观众泪目。国内观众看到的是历史，而海外华人看到的是家人走过的一生。中华文化是他们的来时路，... 查看更多>',
  'count': '3964813',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E3%80%8A%E7%BB%99%E9%98%BF%E5%AC%B7%E7%9A%84%E6%83%85%E4%B9%A6%E3%80%8B%E5%85%A8%E7%90%83%E4%B8%8A%E6%98%A0%E5%A4%A7%E9%A9%AC%E8%A7%82%E4%BC%97%E6%B3%AA%E7%9B%AE&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '42',
  'title': '深圳梧桐山“老虎涧”暴涨成瀑布',
  'subhead': '近日，深圳梧桐山“老虎涧”因暴雨形成瀑布景观，管理部门封闭入口并警示风险。该未开放区域曾发生多起事故，但仍有游客冒险攀爬... 查看更多>',
  'count': '3895981',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%B7%B1%E5%9C%B3%E6%A2%A7%E6%A1%90%E5%B1%B1%E2%80%9C%E8%80%81%E8%99%8E%E6%B6%A7%E2%80%9D%E6%9A%B4%E6%B6%A8%E6%88%90%E7%80%91%E5%B8%83&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '43',
  'title': '曼赞比身价1年从75万欧暴涨至5千万欧',
  'subhead': '北京时间6月19日凌晨，瑞士队在2026年世界杯小组赛第二轮中最后阶段发力，4比1大胜波黑队，拿到本届世界杯的首胜。比赛... 查看更多>',
  'count': '3775335',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E6%9B%BC%E8%B5%9E%E6%AF%94%E8%BA%AB%E4%BB%B71%E5%B9%B4%E4%BB%8E75%E4%B8%87%E6%AC%A7%E6%9A%B4%E6%B6%A8%E8%87%B35%E5%8D%83%E4%B8%87%E6%AC%A7&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '44',
  'title': '“湛江湾1号”成功首捕',
  'subhead': '查看更多>',
  'count': '3677869',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E2%80%9C%E6%B9%9B%E6%B1%9F%E6%B9%BE1%E5%8F%B7%E2%80%9D%E6%88%90%E5%8A%9F%E9%A6%96%E6%8D%95&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '45',
  'title': '专家：女性更年期别再“硬扛”',
  'subhead': '北京协和医院妇科内分泌与生殖医学中心副主任、主任医师陈蓉教授结合我国人口结构变化与临床现状指出，随着人均寿命提升与健康意... 查看更多>',
  'count': '3589686',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%B8%93%E5%AE%B6%EF%BC%9A%E5%A5%B3%E6%80%A7%E6%9B%B4%E5%B9%B4%E6%9C%9F%E5%88%AB%E5%86%8D%E2%80%9C%E7%A1%AC%E6%89%9B%E2%80%9D&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '46',
  'title': '俄方称扎波罗热核电站遭袭',
  'subhead': '查看更多>',
  'count': '3506067',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%BF%84%E6%96%B9%E7%A7%B0%E6%89%8E%E6%B3%A2%E7%BD%97%E7%83%AD%E6%A0%B8%E7%94%B5%E7%AB%99%E9%81%AD%E8%A2%AD&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '47',
  'title': '2026年新能源汽车下乡将启动',
  'subhead': '查看更多>',
  'count': '3432730',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=2026%E5%B9%B4%E6%96%B0%E8%83%BD%E6%BA%90%E6%B1%BD%E8%BD%A6%E4%B8%8B%E4%B9%A1%E5%B0%86%E5%90%AF%E5%8A%A8&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '48',
  'title': '这届世界杯里的中国元素再升级',
  'subhead': '世界杯开幕式上两只LABUBU，让中国品牌火了一波。从南非到巴西，从俄罗斯到卡塔尔，每届世界杯的背后从来都不缺中国身影—... 查看更多>',
  'count': '3302499',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E8%BF%99%E5%B1%8A%E4%B8%96%E7%95%8C%E6%9D%AF%E9%87%8C%E7%9A%84%E4%B8%AD%E5%9B%BD%E5%85%83%E7%B4%A0%E5%86%8D%E5%8D%87%E7%BA%A7&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '49',
  'title': '中方回应韩国涉台表态',
  'subhead': '近日，韩国外交部重申韩中建交联合公报涉台表述，表示承认中华人民共和国政府是中国唯一合法政府，并尊重一个中国立场。中方对此... 查看更多>',
  'count': '3226978',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=%E4%B8%AD%E6%96%B9%E5%9B%9E%E5%BA%94%E9%9F%A9%E5%9B%BD%E6%B6%89%E5%8F%B0%E8%A1%A8%E6%80%81&sa=fyb_news&rsv_dl=fyb_news'},
 {'rank': '50',
  'title': '2026西溪龙舟文化节',
  'subhead': '作为西溪湿地当之无愧的文化“金名片”，端午龙舟竞渡在此传承不息。本届活动在延续民主党派龙舟赛、国际龙船赛、龙舟胜会等多元... 查看更多>',
  'count': '3133813',
  'tag': '',
  'link': 'https://www.baidu.com/s?wd=2026%E8%A5%BF%E6%BA%AA%E9%BE%99%E8%88%9F%E6%96%87%E5%8C%96%E8%8A%82&sa=fyb_news&rsv_dl=fyb_news'}]

### Part 3 - save as csv

In [9]:
import pandas as pd
df = pd.DataFrame(rows)

In [10]:
df.head(5)

,rank,title,subhead,count,tag,link
0,,家国总关情,家国情怀，始终是端午节不变的底色，时隔千年依然引人共鸣。习近平总书记曾深刻指出：“我们是中华...,7904126,,https://www.baidu.com/s?wd=%E5%AE%B6%E5%9B%BD%...
1,1,世界杯开赛后最疯狂一战诞生,在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取...,7809561,热,https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%...
2,2,缅甸总统在上海感叹中国太发达了,6月18日，缅甸总统敏昂莱到访上海临港新片区参观考察，并让随行人员多学习：中国太发达了！ 查...,7713263,新,https://www.baidu.com/s?wd=%E7%BC%85%E7%94%B8%...
3,3,端午节最硬核的“龙舟”竞渡来了,又到一年端午时，一起来看最硬核的“龙舟”竞渡。 查看更多>,7616958,,https://www.baidu.com/s?wd=%E7%AB%AF%E5%8D%88%...
4,4,159瓶茅台被扣押3年后失踪？警方通报,6月18日，四川宜宾警方通报“159瓶茅台被扣押3年后失踪”相关情况称，涉案酒品于2023年...,7520827,新,https://www.baidu.com/s?wd=159%E7%93%B6%E8%8C%...

### Part 3.2 Saving method 1 - append to existing csv

In [11]:
from datetime import datetime

# Add a new column for today's date

# You could just use datetime.now() and get the entire datetime
# or another strftime but this is fine
df['scrape_date'] = datetime.now().strftime("%Y-%m-%d_%H.%M")
df.head()

,rank,title,subhead,count,tag,link,scrape_date
0,,家国总关情,家国情怀，始终是端午节不变的底色，时隔千年依然引人共鸣。习近平总书记曾深刻指出：“我们是中华...,7904126,,https://www.baidu.com/s?wd=%E5%AE%B6%E5%9B%BD%...,2026-06-18_23.05
1,1,世界杯开赛后最疯狂一战诞生,在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取...,7809561,热,https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%...,2026-06-18_23.05
2,2,缅甸总统在上海感叹中国太发达了,6月18日，缅甸总统敏昂莱到访上海临港新片区参观考察，并让随行人员多学习：中国太发达了！ 查...,7713263,新,https://www.baidu.com/s?wd=%E7%BC%85%E7%94%B8%...,2026-06-18_23.05
3,3,端午节最硬核的“龙舟”竞渡来了,又到一年端午时，一起来看最硬核的“龙舟”竞渡。 查看更多>,7616958,,https://www.baidu.com/s?wd=%E7%AB%AF%E5%8D%88%...,2026-06-18_23.05
4,4,159瓶茅台被扣押3年后失踪？警方通报,6月18日，四川宜宾警方通报“159瓶茅台被扣押3年后失踪”相关情况称，涉案酒品于2023年...,7520827,新,https://www.baidu.com/s?wd=159%E7%93%B6%E8%8C%...,2026-06-18_23.05

Check what already exists

In [12]:
# If it exists, open it
# If it doesn't, just make a blank dataframe
# could also use os.path.exists to check if the file exists
# but honestly try/except is the easiest route to go here
try:
    existing_df = pd.read_csv("baidu-scrape1.csv")
except:
    existing_df = pd.DataFrame([])
existing_df.head()

,rank,title,subhead,count,tag,link,scrape_date
0,NaN,永远的“四大队”,在中国共产党成立105周年之际，习近平总书记在给新华社102岁老党员张连生回信中表示：“您在...,7904844,NaN,https://www.baidu.com/s?wd=%E6%B0%B8%E8%BF%9C%...,2026-06-18_22.48
1,1.0,世界杯开赛后最疯狂一战诞生,在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取...,7809639,热,https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%...,2026-06-18_22.48
2,2.0,缅甸总统在上海感叹中国太发达了,6月18日，缅甸总统敏昂莱到访上海临港新片区参观考察，并让随行人员多学习：中国太发达了！ 查...,7714018,新,https://www.baidu.com/s?wd=%E7%BC%85%E7%94%B8%...,2026-06-18_22.48
3,3.0,让AI走进千家万户,6月18日，商务部等八部门发布《关于加快“人工智能+消费”发展的实施意见》，围绕提升人工智能...,7616494,NaN,https://www.baidu.com/s?wd=%E8%AE%A9AI%E8%B5%B...,2026-06-18_22.48
4,4.0,民房“一窗6店” 被质疑是幽灵外卖,近日，广东东莞一处民房通过单一窗户同时运营6家外卖店铺，外卖员反映店铺前后门紧闭，餐食仅通过...,7523476,新,https://www.baidu.com/s?wd=%E6%B0%91%E6%88%BF%...,2026-06-18_22.48

In [13]:
# Combine our new dataframe and our old dataframe
# ignore_index=True 
combined = pd.concat([df, existing_df], ignore_index=True)
combined.head()

,rank,title,subhead,count,tag,link,scrape_date
0,,家国总关情,家国情怀，始终是端午节不变的底色，时隔千年依然引人共鸣。习近平总书记曾深刻指出：“我们是中华...,7904126,,https://www.baidu.com/s?wd=%E5%AE%B6%E5%9B%BD%...,2026-06-18_23.05
1,1,世界杯开赛后最疯狂一战诞生,在北京时间6月19日结束的世界杯B组第2轮1场对决中，最疯狂一战诞生，瑞士4-1完胜波黑，取...,7809561,热,https://www.baidu.com/s?wd=%E4%B8%96%E7%95%8C%...,2026-06-18_23.05
2,2,缅甸总统在上海感叹中国太发达了,6月18日，缅甸总统敏昂莱到访上海临港新片区参观考察，并让随行人员多学习：中国太发达了！ 查...,7713263,新,https://www.baidu.com/s?wd=%E7%BC%85%E7%94%B8%...,2026-06-18_23.05
3,3,端午节最硬核的“龙舟”竞渡来了,又到一年端午时，一起来看最硬核的“龙舟”竞渡。 查看更多>,7616958,,https://www.baidu.com/s?wd=%E7%AB%AF%E5%8D%88%...,2026-06-18_23.05
4,4,159瓶茅台被扣押3年后失踪？警方通报,6月18日，四川宜宾警方通报“159瓶茅台被扣押3年后失踪”相关情况称，涉案酒品于2023年...,7520827,新,https://www.baidu.com/s?wd=159%E7%93%B6%E8%8C%...,2026-06-18_23.05

In [14]:
combined.to_csv("baidu-scrape1.csv", index=False)